### ISSUE TITLE
Scaling Dataset

### ISSUE THREAD

**Issue by sureshhewabi** [SBCS-Bioinformatics/R-Core#24]

**Comment by Nazrath10R** [comment]
added code which checks the data and automatically log2 transforms it, if needed

should provide a good solution for the user and it would be nice to show this on a boxplot

code needs to be tested on different datasets

we could potentially look into other types of transformations, e.g: Benjamini & Yekutiell, Hochberg, Holm, Hommel, Bonferroni

**Comment by Nazrath10R** [comment]
NCBI's comments on scaling

Apply adjustment to the P-values: Limma provides several P-value adjustment options. These adjustments, also called multiple-testing corrections, attempt to correct for the occurrence of false positive results. The Benjamini & Hochberg false discovery rate method is selected by default because it is the most commonly used adjustment for microarray data and provides a good balance between discovery of statistically significant genes and limitation of false positives. If you want to change the adjustment method, go to the Options tab and select another method. References for each method are provided below. The adjusted P-values are listed in the Adj P-value column of the results table.

Apply log transformation to the data: The GEO database accepts a variety of data value types, including logged and unlogged data. Limma expects data values to be in log space. To address this, GEO2R has an auto-detect feature that checks the values of selected Samples and automatically performs a log2 transformation on values determined not to be in log space. Alternatively, the user can select Yes to force log2 transformation, or No to override the auto-detect feature. The auto-detect feature only considers Sample values that have been assigned to a group, and applies the transformation in an all-or-none fashion.
